import {createHash} from 'node:crypto';
import webpush from 'web-push';
export const subscriptionsPath='arcane_push_subscriptions';
export const vapidPublic=process.env.VAPID_PUBLIC_KEY||'';
const vapidPrivate=process.env.VAPID_PRIVATE_KEY||'';
const vapidSubject=process.env.VAPID_SUBJECT||'';
if(vapidPublic&&vapidPrivate&&vapidSubject)webpush.setVapidDetails(vapidSubject,vapidPublic,vapidPrivate);
export const pushConfigured=Boolean(vapidPublic&&vapidPrivate&&vapidSubject);
export function subscriptionId(endpoint){return createHash('sha256').update(endpoint).digest('hex')}
export function validSubscription(value){if(!value||typeof value!=='object'||typeof value.endpoint!=='string'||value.endpoint.length>2048||!value.endpoint.startsWith('https://')||!value.keys||typeof value.keys.p256dh!=='string'||typeof value.keys.auth!=='string'||value.keys.p256dh.length>512||value.keys.auth.length>512)return false;try{const host=new URL(value.endpoint).hostname;return ['push.apple.com','push.services.mozilla.com','fcm.googleapis.com','updates.push.services.mozilla.com'].some(domain=>host===domain||host.endsWith('.'+domain))}catch{return false}}
export async function dispatchReminders(db,now=Date.now()){if(!pushConfigured)throw Error('Push not configured');const tasks=await db.collection('arcane_assignments').where('done','==',false).get();const devices=await db.collection(subscriptionsPath).get();const reminders=db.collection('arcane_push_deliveries');let sent=0;for(const doc of tasks.docs){const item=doc.data(),due=item.due;if(!Number.isSafeInteger(due))continue;const remaining=due-now;const kind=remaining>0&&remaining<=24*3600000?'due-soon':remaining<=0&&remaining>=-24*3600000?'overdue':null;if(!kind)continue;const title=kind==='overdue'?'Quest overdue':'Quest due within 24 hours';const body=`${String(item.title||'An assignment').slice(0,100)} ${kind==='overdue'?'is overdue.':'is due soon.'}`;for(const device of devices.docs){const delivery=reminders.doc(subscriptionId(`${device.id}:${doc.id}:${kind}:${due}`));try{await delivery.create({taskId:doc.id,deviceId:device.id,kind,due,createdAt:now})}catch(error){if(error.code===6)continue;throw error}try{await webpush.sendNotification(device.data().subscription,JSON.stringify({title,body,tag:`${doc.id}-${kind}`}),{TTL:3600});sent++}catch(error){await delivery.delete().catch(()=>{});if(error.statusCode===404||error.statusCode===410)await device.ref.delete().catch(()=>{});else console.error('Push delivery failed',error.statusCode||error.message)}}}return {sent}}
